<a href="https://colab.research.google.com/github/NiranjanJamkhande/imdb-review-nlp-problem/blob/main/IMDB_nlp_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r'/content/drive/MyDrive/Datasets ML/IMDB Dataset.csv')

In [ ]:
df.shape

(50000, 2)

In [ ]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.4.1'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
### Vocabulary size
voc_size = 10000

In [ ]:
import nltk
import re

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
!pip install wordcloud

In [ ]:
from nltk.corpus import stopwords
stops = stopwords.words('english')

from wordcloud import STOPWORDS
stops = set(STOPWORDS)
stops.add("br")

In [ ]:
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

ps = PorterStemmer()
wordnet = WordNetLemmatizer()

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [ ]:
corpus = []
for i in range(0, 50000):
    review = re.sub('[^a-zA-Z]', ' ', df['review'][i])
    # meaning of above line is,...
    # by using re.sub, apart from a-z and A-Z, replace everything by ' ',
    # and do it for all sentences.
    # ^ says = not in or apart from
    review = review.lower()
    review = review.split()
    review = [wordnet.lemmatize(word) for word in review if not word in set(stops)]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus

['one reviewer mentioned watching oz episode ll hooked right exactly happened first thing struck oz brutality unflinching scene violence set right word go trust show faint hearted timid show pull punch regard drug sex violence hardcore classic use word called oz nickname given oswald maximum security state penitentary focus mainly emerald city experimental section prison cell glass front face inwards privacy high agenda em city home many aryan muslim gangsta latino christian italian irish scuffle death stare dodgy dealing shady agreement never far away say main appeal show due fact go show wouldn t dare forget pretty picture painted mainstream audience forget charm forget romance oz doesn t mess around first episode saw struck nasty surreal couldn t say ready watched developed taste oz got accustomed high level graphic violence violence injustice crooked guard ll sold nickel inmate ll kill order away well mannered middle class inmate turned prison bitch due lack street skill prison exp

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[9101,
  663,
  1949,
  6301,
  5580,
  4542,
  712,
  8916,
  2254,
  5655,
  8936,
  2545,
  630,
  3727,
  5580,
  3668,
  1080,
  2615,
  7122,
  1768,
  2254,
  9338,
  767,
  4493,
  2796,
  9199,
  8122,
  3165,
  2796,
  8432,
  6795,
  6824,
  2984,
  2734,
  7122,
  1644,
  2891,
  2059,
  9338,
  7281,
  5580,
  275,
  8245,
  5693,
  7357,
  4482,
  2930,
  4742,
  9172,
  4231,
  7817,
  7942,
  7936,
  6726,
  7807,
  3712,
  4994,
  9589,
  7182,
  1010,
  9165,
  8922,
  5368,
  1174,
  7942,
  4479,
  8885,
  4847,
  5098,
  6736,
  1555,
  8070,
  6818,
  4471,
  5791,
  3611,
  7471,
  8827,
  1821,
  2530,
  5056,
  7499,
  1798,
  5197,
  751,
  665,
  8313,
  2796,
  7411,
  622,
  767,
  2796,
  485,
  2733,
  6841,
  2644,
  7242,
  9788,
  5110,
  1399,
  6738,
  2644,
  5201,
  2644,
  7466,
  5580,
  7272,
  2733,
  4307,
  2988,
  2545,
  4542,
  1044,
  3727,
  9525,
  6685,
  1281,
  2733,
  751,
  504,
  5188,
  7126,
  3771,
  5580,
  7102,
  2680,
  89

**Embedding Representation**

In [ ]:
sent_length=100
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)

In [ ]:
print(embedded_docs)

[[4847 5098 6736 ... 9265 1291 8375]
 [   0    0    0 ... 4549 9074 4412]
 [   0    0    0 ...  767 3934  829]
 ...
 [1528 2226 5736 ... 1528 3999 6205]
 [3075 4052 8852 ... 4962 4629 2516]
 [   0    0    0 ... 4905 3555 6834]]


In [ ]:
embedded_docs[5896]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 4364,
       9034, 8580, 3711, 8443, 3070,  491, 4458, 5481, 9029, 1341, 1850,
       5510,   31, 9431, 1032, 7279, 5922, 8624, 2395, 6271, 6125, 7087,
       9841, 2475, 1908, 8344, 3064, 5090, 4040, 6805, 9620, 9222,   74,
       6198, 2593, 5483, 5385, 9805, 8462, 4497, 6805, 8388, 9095, 8479,
       8752], dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=200
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 100, 200)          2000000   
_________________________________________________________________
lstm (LSTM)                  (None, 100)               120400    
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 2,120,501
Trainable params: 2,120,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
y = df.iloc[:, 1]
y = pd.get_dummies(y, drop_first=True)

In [ ]:
y

positive
0             1
1             1
2             1
3             0
4             1
...         ...
49995         1
49996         0
49997         0
49998         0
49999         0

[50000 rows x 1 columns]

In [ ]:
y.shape

(50000, 1)

In [ ]:
len(embedded_docs),y.shape

(50000, (50000, 1))

In [ ]:
X=np.array(embedded_docs)
y=np.array(y)

In [ ]:
X.shape, y.shape

((50000, 100), (50000, 1))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

**Model Training**

In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=50,batch_size=64)

Epoch 1/50
547/547 [==============================] - 28s 36ms/step - loss: 0.4459 - accuracy: 0.7851 - val_loss: 0.3296 - val_accuracy: 0.8606
Epoch 2/50
547/547 [==============================] - 18s 34ms/step - loss: 0.2373 - accuracy: 0.9071 - val_loss: 0.3370 - val_accuracy: 0.8562
Epoch 3/50
547/547 [==============================] - 18s 34ms/step - loss: 0.1750 - accuracy: 0.9347 - val_loss: 0.3778 - val_accuracy: 0.8510
Epoch 4/50
547/547 [==============================] - 18s 33ms/step - loss: 0.1225 - accuracy: 0.9556 - val_loss: 0.4504 - val_accuracy: 0.8473
Epoch 5/50
547/547 [==============================] - 18s 33ms/step - loss: 0.0918 - accuracy: 0.9675 - val_loss: 0.4964 - val_accuracy: 0.8375
Epoch 6/50
547/547 [==============================] - 18s 33ms/step - loss: 0.0691 - accuracy: 0.9771 - val_loss: 0.5502 - val_accuracy: 0.8442
Epoch 7/50
547/547 [==============================] - 18s 33ms/step - loss: 0.0512 - accuracy: 0.9839 - val_loss: 0.6916 - val_accuracy:

**Performance Metrics And Accuracy**

In [ ]:
y_pred=model.predict_classes(X_test)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, accuracy_score

In [ ]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test,y_pred))


[[6178 1233]
 [1204 6385]]
              precision    recall  f1-score   support

           0       0.84      0.83      0.84      7411
           1       0.84      0.84      0.84      7589

    accuracy                           0.84     15000
   macro avg       0.84      0.84      0.84     15000
weighted avg       0.84      0.84      0.84     15000

0.8375333333333334


**Adding dropouts**

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=100
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
y_pred=model.predict_classes(X_test)

In [ ]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test,y_pred))